<a href="https://colab.research.google.com/github/anichhabra91/LoanPredictionApp_1/blob/main/Loan_Prediction_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.model_selection import train_test_split

In [ ]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [ ]:
train.shape

(614, 13)

In [ ]:
test.shape

(367, 12)

In [ ]:
train
#[1, 0, 0, 0, 103, 2900.0, 131.0, 360.0, 1.0, 1]

Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0    LP001002    Male      No         0.0      Graduate            No   
1    LP001003    Male     Yes         1.0      Graduate            No   
2    LP001005    Male     Yes         0.0      Graduate           Yes   
3    LP001006    Male     Yes         0.0  Not Graduate            No   
4    LP001008    Male      No         0.0      Graduate            No   
..        ...     ...     ...         ...           ...           ...   
609  LP002978  Female      No         0.0      Graduate            No   
610  LP002979    Male     Yes         3.0      Graduate            No   
611  LP002983    Male     Yes         1.0      Graduate            No   
612  LP002984    Male     Yes         2.0      Graduate            No   
613  LP002990  Female      No         0.0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [ ]:
data=pd.concat([train,test])

In [ ]:
data.drop("Loan_ID",axis=1,inplace=True)

In [ ]:
data.isnull().sum()

Gender                24
Married                3
Dependents            25
Education              0
Self_Employed         55
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            27
Loan_Amount_Term      20
Credit_History        79
Property_Area          0
Loan_Status          367
dtype: int64

In [ ]:
for i in [data]:
  i["Gender"]=i["Gender"].fillna(data.Gender.dropna().mode()[0])
  i["Dependents"]=i["Dependents"].fillna(data.Dependents.dropna().mode()[0])
  i["Self_Employed"]=i["Self_Employed"].fillna(data.Self_Employed.dropna().mode()[0])
  i["Credit_History"]=i["Credit_History"].fillna(data.Credit_History.dropna().mode()[0])
data.isnull().sum()

Gender                 0
Married                3
Dependents             0
Education              0
Self_Employed          0
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            27
Loan_Amount_Term      20
Credit_History         0
Property_Area          0
Loan_Status          367
dtype: int64

In [ ]:
data.LoanAmount = data.LoanAmount.fillna(data.LoanAmount.mean())
data.Loan_Amount_Term = data.Loan_Amount_Term.fillna(360.0)
data.Married = data.Married.fillna('Yes')

In [ ]:
data.isnull().sum()

Gender                 0
Married                0
Dependents             0
Education              0
Self_Employed          0
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount             0
Loan_Amount_Term       0
Credit_History         0
Property_Area          0
Loan_Status          367
dtype: int64

In [ ]:
data

Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
0     Male      No         0.0      Graduate            No             5849   
1     Male     Yes         1.0      Graduate            No             4583   
2     Male     Yes         0.0      Graduate           Yes             3000   
3     Male     Yes         0.0  Not Graduate            No             2583   
4     Male      No         0.0      Graduate            No             6000   
..     ...     ...         ...           ...           ...              ...   
362   Male     Yes         3.0  Not Graduate           Yes             4009   
363   Male     Yes         0.0      Graduate            No             4158   
364   Male      No         0.0      Graduate            No             3250   
365   Male     Yes         0.0      Graduate            No             5000   
366   Male      No         0.0      Graduate           Yes             9200   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0   142.51153             360.0             1.0   
1               1508.0   128.00000             360.0             1.0   
2                  0.0    66.00000             360.0             1.0   
3               2358.0   120.00000             360.0             1.0   
4                  0.0   141.00000             360.0             1.0   
..                 ...         ...               ...             ...   
362             1777.0   113.00000             360.0             1.0   
363              709.0   115.00000             360.0             1.0   
364             1993.0   126.00000             360.0             1.0   
365             2393.0   158.00000             360.0             1.0   
366                0.0    98.00000             180.0             1.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
362         Urban         NaN  
363         Urban         NaN  
364     Semiurban         NaN  
365         Rural         NaN  
366         Rural         NaN  

[981 rows x 12 columns]

In [ ]:
new_train=data.iloc[:614]
new_test=data.iloc[614:]

In [ ]:
new_train

Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No         0.0      Graduate            No             5849   
1      Male     Yes         1.0      Graduate            No             4583   
2      Male     Yes         0.0      Graduate           Yes             3000   
3      Male     Yes         0.0  Not Graduate            No             2583   
4      Male      No         0.0      Graduate            No             6000   
..      ...     ...         ...           ...           ...              ...   
609  Female      No         0.0      Graduate            No             2900   
610    Male     Yes         3.0      Graduate            No             4106   
611    Male     Yes         1.0      Graduate            No             8072   
612    Male     Yes         2.0      Graduate            No             7583   
613  Female      No         0.0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0   142.51153             360.0             1.0   
1               1508.0   128.00000             360.0             1.0   
2                  0.0    66.00000             360.0             1.0   
3               2358.0   120.00000             360.0             1.0   
4                  0.0   141.00000             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0    71.00000             360.0             1.0   
610                0.0    40.00000             180.0             1.0   
611              240.0   253.00000             360.0             1.0   
612                0.0   187.00000             360.0             1.0   
613                0.0   133.00000             360.0             0.0   

    Property_Area Loan_Status  
0           Urban           Y  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[614 rows x 12 columns]

In [ ]:
X = new_train.iloc[:, 0: 11].values
y = new_train.iloc[:, 11].values

In [ ]:
X[0]

array(['Male', 'No', 0.0, 'Graduate', 'No', 5849, 0.0, 142.51153039832286,
       360.0, 1.0, 'Urban'], dtype=object)

In [ ]:
y

array(['Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()

for i in range(0, 5):
    X_train[:,i] = labelencoder_X.fit_transform(X_train[:,i])

X_train[:,10] = labelencoder_X.fit_transform(X_train[:,10])


labelencoder_y = LabelEncoder()
y_train = labelencoder_y.fit_transform(y_train)
print(X_train[2])


[1 1 0 0 0 3948 1733.0 149.0 360.0 0.0 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
for i in range(0, 5):
    X_test[:,i] = labelencoder_X.fit_transform(X_test[:,i])
X_test[:,10] = labelencoder_X.fit_transform(X_test[:,10])
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y_test = labelencoder_y.fit_transform(y_test)

In [ ]:

X_test

array([[1, 0, 0, ..., 360.0, 1.0, 1],
       [0, 0, 0, ..., 360.0, 1.0, 1],
       [1, 1, 0, ..., 360.0, 1.0, 2],
       ...,
       [1, 1, 0, ..., 360.0, 1.0, 1],
       [1, 1, 3, ..., 180.0, 0.0, 2],
       [1, 1, 1, ..., 360.0, 1.0, 2]], dtype=object)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
X_train

array([[1, 1, 0, ..., 360.0, 1.0, 1],
       [1, 0, 1, ..., 360.0, 1.0, 1],
       [1, 1, 0, ..., 360.0, 0.0, 0],
       ...,
       [1, 1, 3, ..., 360.0, 1.0, 1],
       [1, 1, 0, ..., 360.0, 1.0, 2],
       [0, 1, 0, ..., 360.0, 1.0, 1]], dtype=object)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn import metrics
print('The accuracy of Logistic Regression is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of Logistic Regression is:  0.8292682926829268


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[15 18]
 [ 3 87]]


In [ ]:
!pip install flask-ngrok


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pickle
pickle.dump(classifier, open('model.pkl','wb'))


model = pickle.load(open('model.pkl','rb'))


In [ ]:
!pip install pyngrok


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
! ngrok authtoken 2AjxXxBBI8aGECuXOOGIHbCmeDI_4GkBz6LyvcTPfobdGfSQz
     

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from flask import *
from flask_ngrok import run_with_ngrok

In [ ]:
app=Flask(__name__)
run_with_ngrok(app)

In [ ]:
import numpy as np
from flask import Flask, render_template,request
import pickle#Initialize the flask App
model = pickle.load(open('model.pkl', 'rb'))
@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
    #For rendering results on HTML GUI
    int_features = [int(x) for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction=model.predict(final_features)
    if prediction[0]==1:
        output="LOAN APPROVED!"
    else:
        output="SORRY,Your Loan Cant Be Approved :("
    return render_template('index.html', prediction_text=output)
   

In [ ]:

app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://4471-34-147-53-233.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


INFO:werkzeug:127.0.0.1 - - [05/Jan/2023 14:19:27] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jan/2023 14:19:27] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Jan/2023 14:20:07] "POST /predict HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jan/2023 14:21:39] "POST /predict HTTP/1.1" 200 -
